### ISSUE TITLE
Job validation and submission raise contradictory messages: "job is valid" VS "Internal server error"

### ISSUE THREAD

**Issue by zeineb** [ow2-proactive/scheduling-portal#402]
<img width="595" alt="submit" src="https://user-images.githubusercontent.com/368264/34376073-34d33022-eaea-11e7-87d5-c13e052856e6.png">
<img width="598" alt="check" src="https://user-images.githubusercontent.com/368264/34376074-34ea7d68-eaea-11e7-9153-3062354fcc88.png">

**Comment by amouhoub** [comment]
@zeineb This is not just portal-related,,, the job planner as well doesn't accept files like the one you tried (calcul(7).xml).
The workflow model has changed (since Yaro's last changes. @ShatalovYaroslav what is you opinion on this ?), and therefore, some workflow files are not longer valid. We should think about a retro-compatibility for legacy workflow files

**Comment by zeineb** [comment]
@amouhoub I tried to perform the same operations on Studio (check/submit) on the same workflow (calcul(7).xml) and it raised no issue.

**Comment by amouhoub** [comment]
@zeineb is it successfully executed? (did you check in the scheduler? )

**Comment by amouhoub** [comment]
Jobs are successfully executed if you check "execute as soon as possible".
This issue is job-planner related, due to some change in the execution-calendars model. Precisely,  the "name" value should not be in the EXECUTION_CALENDARS.
A possible fix is to ignore the "name" if existant...

**Comment by amouhoub** [comment]
Fixed in PR: https://bitbucket.org/activeeon/job-planner/pull-requests/66/fix-rejected-jobs-with-name-in
